import argparse
import ast

def args_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", "-data", type=str, default="CIFAR10", help="Name of dataset (e.g. CIFAR10, CIFAR100)")
    parser.add_argument("--method", type=str, default="proposed", help="Name of method")
    parser.add_argument("--model_type", type=str, default="CNN", help="Type of model (e.g. CNN, ResNet18)")
    parser.add_argument("--distribution_shifting", action="store_true", help="Whether to use distribution shifting")
    parser.add_argument("--class_increment", action="store_true", help="Whether to use class increment")
    parser.add_argument("--data_distribution_alpha", type=int, default=1, help="Dirichlet distribution alpha for client data distribution")
    parser.add_argument("--num_clients", type=int, default=10, help="Number of clients")
    parser.add_argument("--num_rounds", type=int, default=400, help="Max number of global rounds (train until no more new data)")
    parser.add_argument("--batch_size", type=int, default=64, help="Local batch size")
    parser.add_argument("--test_batch_size", type=int, default=100, help="Test batch size")
    parser.add_argument("--new_distribution_weight", type=float, default=0.1, help="Data distribution change ratio (only available when distribution_shifting is True)")
    parser.add_argument("--data_size_gain_ratio", type=float, default=0.1, help="Data size change ratio")
    parser.add_argument("--new_data_size_distribution_weight", type=float, default=0.5, help="Data size distribution change ratio")
    parser.add_argument("--rounds_to_get_new_data", type=int, default=100, help="Suppose rounds to get all data")
    parser.add_argument("--data_size_alphas", type=str, default="[3.7, 8.2, 10.0, 11.0, 3.3, 6.6, 5.5, 7.4, 4.2, 3.1]", help="Dirichlet distribution alphas for initial data size distribution (e.g. \"[3.7, 8.2, 10.0, 11.0, 3.3, 6.6, 5.5, 7.4, 4.2, 3.1]\")")
    parser.add_argument("--start_class_num", type=int, default=5, help="Starting number of classes for each client (only available when class_increment is True)")
    parser.add_argument("--increment_period", type=int, default=20, help="Period of another one class to join (only available when class_increment is True)")
    parser.add_argument("--random_seed", type=int, default=42, help="Random seed")
    parser.add_argument("--epochs_per_client", "-epoch", type=int, default=5, help="Number of local epochs per client")
    parser.add_argument("--learning_rate", "-lr", type=float, default=0.01, help="Learning rate for local training")
    parser.add_argument("--participate_ratio", type=float, default=0.8, help="Participate ratio of clients in each round")
    parser.add_argument("--alpha", type=float, default=1, help="Alpha parameter for the proposed method")
    parser.add_argument("--beta", type=float, default=1, help="Beta parameter for the proposed method")
    parser.add_argument("--gamma", type=float, default=1, help="Gamma parameter for the proposed method")
    parser.add_argument("--temperature", type=float, default=0.8, help="Temperature parameter for the proposed method")
    parser.add_argument("--cs_threshold", type=float, default=0.5, help="cosine similarity threshold for client selection")
    parser.add_argument("--kl_threshold", type=float, default=0.01, help="KL divergence threshold for client selection")
    parser.add_argument("--kl_epsilon", type=float, default=1e-10, help="Epsilon for KL divergence calculation")
    parser.add_argument("--log_file", type=str, default="Log10.log", help="Log file name")
    args = parser.parse_args()
    args.data_size_alphas = ast.literal_eval(args.data_size_alphas)
    return args